# Generated by Django 2.2.1 on 2019-07-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190708_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='category',
            new_name='topic',
        ),
    ]
